### ISSUE TITLE
Default transport mechanism not read from configuration

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-workflows#102]
With an appropriate site configuration file (setting `zocalo.default_transport: OfflineTransport`) the call
```
zocalo.wrap -e offline --help | grep "(default:"
```
should show `OfflineTransport`, yet it sticks with `StompTransport`.

**Comment by rjgildea** [comment]
This wasn't a bug in workflows/zocalo, but the configuration file in question hadn't been updated to use the `transport` plugin introduced in https://github.com/DiamondLightSource/python-workflows/commit/73ba66bf66d7927d2cdcc07ed39874ba27b93a26, i.e.:
```
 offline-default-transport:
-  plugin: storage
-  zocalo.default_transport: OfflineTransport
+  plugin: transport
+  default: OfflineTransport
```
