### ISSUE TITLE
Temporary queues

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-workflows#105]
An issue to gather requirements to facilitate finding a suitable API (for #87, #100, and others)

#### Subscriptions to a topic (=Fanout exchange or similar)
In RabbitMQ you can only subscribe to a queue. This can be a personal queue just for the listener, it can be connection-bound (so will self-destruct on disconnect), and it could be time-limited.
For a standard topic subscription a connection-bound queue is sufficient. The name of the queue is irrelevant, as it would not be passed on to anyone else. The queue needs to be bound to the relevant exchange, potentially with a custom binding key.
This is used for example in `dlstbx.status_monitor` and in the Controller, listening out to service and wrapper status broadcasts.

#### Command queue
This is really the same as above, except that we don't want this to break reconnectability. If the connection is broken while this subscription exists then it should just be reconnected. During the offline period we may miss messages but this is fine.
This is used in all services, where the outer process listens out to `dlstbx.shutdown` type messages.

#### Return channel for messages
In this case we want a temporary queue that we can receive answers on. For this we need a queue name (rather: something that is addressable via some exchange) to give to some other process so that answers can reach our queue. This is only really used in system tests. Reconnectability is not really a concern here - if the connection fails then the test can just fail. The actual queue/return address name may be determined by the client library or server, the important bit is that the API returns something that can be passed to the other process.
This is used in system tests to direct output back to the test-initiating process.

Am I missing any use cases?

**Comment by ndevenish** [comment]
Return channel is also used by anything outside Zocalo that wants to use results from Zocalo - at the moment the only instance I know of that does this is the I24 PIA

**Comment by Anthchirp** [comment]
These three use cases then could map to the following?

Use case | Workflows common transport function call | StompTransport | PikaTransport
-- | -- | -- | --
Topic subscription | `Transport().subscribe_broadcast()` | No special treatment required | Creates a queue internally, name irrelevant, lifetime limited to connection
Command queue |  `Transport().subscribe_broadcast(reconnectable=True)` | No special treatment required | Creates a queue internally, name irrelevant, lifetime limited to connection, on reconnection create a new queue. In this case there may be a period in which messages are lost, this is acceptable.
Return channel | `Transport().subscribe_temporary(name_hint: Optional[str], callback, binding?: Optional[TBD], **kwargs) -> NamedTuple[subscription_id:int, name:str]` | calls `subscribe()` internally, uses a random name if hint is not specified, ensures name is prefixed with `transient.` | creates a queue, binds queue to exchange using binding hints, subscribes to queue. Lifetime of queue is tied to the connection, thus reconnection logic is disabled.

**Comment by rjgildea** [comment]
I _think_ the first two use cases are already handled by the `subscribe_broadcast()`/`_add_subscription()` methods of `PikaThread`:
https://github.com/DiamondLightSource/python-workflows/blob/dc23b8a7d9b91b3b8c11f830192812149b556b44/src/workflows/transport/pika_transport.py#L1176-L1182
So all we need is to decide on the desired interface for the last use case. The previously discussed options, plus the one you've suggested above are:
1. Addition of optional parameter `temporary=True` to the existing `transport.subscribe()` method
```
transport.subscribe(..., temporary=True)
```
(implemented in https://github.com/DiamondLightSource/python-workflows/pull/87/files)
2. Explicit declaration of the temporary queue by a new `transport.queue_declare(..., temporary=True)`
```
queue = transport.queue_declare(..., temporary=True)
transport.subscribe(queue)
```
3. A new `transport.subscribe_temporary()` method as suggested above:
```
transport.subscribe_temporary()
```
I have no strong opinions which approach is best (other than to point out that we already have putative implementations of the first two).
