### ISSUE TITLE
Service slowed down by frontend

### ISSUE THREAD

**Issue by Anthchirp** [DiamondLightSource/python-workflows#36]
@rjgildea reports the service can be slowed down in
https://github.com/DiamondLightSource/python-workflows/blob/3fa50ed44a6f68e3aec2f712535d8c88fc91bce5/workflows/services/common_service.py#L153-L156
by the frontend. Presumably the receiver loop around
https://github.com/DiamondLightSource/python-workflows/blob/3fa50ed44a6f68e3aec2f712535d8c88fc91bce5/workflows/frontend/__init__.py#L179
is slower than necessary and could do with some optimisation

**Comment by rjgildea** [comment]
```
$ cat services/fake_news.py 
import time
import workflows.recipe
from workflows.services.common_service import CommonService


class FakeNews(CommonService):

    # Human readable service name
    _service_name = "Fake News"

    # Logger name
    _logger_name = "services.fake_news"

    def initializing(self):
        t0 = time.perf_counter()
        N = 1000
        for i in range(N):
            self.log.info(f"FAKE NEWS #{i}")
        t1 = time.perf_counter()
        self.log.info(f"Time taken to log {N} FAKE NEWS messages: {t1 - t0} seconds")
```

```
$ dlstbx.service --test -s FakeNews
FAKE NEWS #0
...
FAKE NEWS #999
Time taken to log 1000 FAKE NEWS messages: 14.247174648568034 seconds
```

The above is with graylog enabled. With graylog disabled, time drops to ~11 seconds.

**Comment by rjgildea** [comment]
For comparison:
```
import logging
logging.basicConfig(
    level=logging.DEBUG, format="%(message)s"
)
fake_news = FakeNews()
fake_news.initializing()
```

```
FAKE NEWS #0
...
FAKE NEWS #999
Time taken to log 1000 FAKE NEWS messages: 0.047825075685977936 seconds
```

**Comment by Anthchirp** [comment]
Should be fixed by DiamondLightSource/python-zocalo@d31bc106b277b81aab071577d1e3287de6024e6f

**Comment by Anthchirp** [comment]
Change improved the situation from 14/15 seconds to 11, but there is still plenty of scope.

**Comment by Anthchirp** [comment]
```
Time taken to log 1000 FAKE NEWS messages: 0.31661009043455124 seconds
```
Upcoming dlstbx commit to blame.
